# Generated by Django 5.2.6 on 2026-10-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLimit',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
