# Generated by Django 5.2.6 on 2026-10-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='request_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
