# Generated by Django 5.2.6 on 2026-10-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_request_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='group',
            field=models.CharField(choices=[('inspiration', 'Inspiration'), ('brand', 'Brand'), ('people', 'Photos of the client'), ('project', 'Project'), ('message', 'Message')], max_length=20),
        ),
    ]
