# Generated by Django 5.2.6 on 2026-10-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_microsoftmailcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftMailAuthorization',
            fields=[
                ('state_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('encrypted_flow', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
