# Generated by Django 5.2.6 on 2026-09-27 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBrief',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('archived', 'Archived')], db_index=True, default='new', max_length=16)),
                ('company', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('overview', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('success', models.TextField(blank=True)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('goal', models.CharField(blank=True, max_length=100)),
                ('offerings', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('inspiration_link', models.URLField(blank=True, max_length=1000)),
                ('domain', models.CharField(blank=True, max_length=253)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('brand', models.TextField(blank=True)),
                ('integrations', models.TextField(blank=True)),
                ('package', models.CharField(blank=True, max_length=100)),
                ('referral', models.CharField(blank=True, max_length=200)),
                ('social_urls', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
