# Generated by Django 5.2.6 on 2026-10-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbrief',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
