# Generated by Django 5.2.6 on 2026-10-03 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0002_alter_projectbrief_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbrief',
            name='confirmation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectbrief',
            name='confirmation_nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='projectbrief',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
