# Generated by Django 5.2.6 on 2026-10-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0003_projectbrief_confirmation_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbrief',
            name='acquisition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectbrief',
            name='business_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='projectbrief',
            name='content_readiness',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='projectbrief',
            name='service_interest',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
