export const tickerItems = [
  { label: "Full-stack development", service: "full-stack-development" },
  { label: "Web design", service: "web-design" },
  { label: "Shopify websites", service: "web-design" },
  { label: "React + Vite", service: "full-stack-development" },
  { label: "Django + Python APIs", service: "full-stack-development" },
  { label: "Node + Express", service: "full-stack-development" },
  { label: "PostgreSQL databases", service: "full-stack-development" },
  { label: "API integrations", service: "api-integrations" },
  { label: "Stripe payments", service: "api-integrations" },
  { label: "MCP servers", service: "api-integrations" },
  { label: "Booking systems", service: "full-stack-development" },
  { label: "Admin dashboards", service: "full-stack-development" },
  { label: "Mobile apps · React Native", service: "full-stack-development" },
  { label: "SEO + AEO", service: "seo-aeo" },
  { label: "AI search optimization", service: "seo-aeo" },
  { label: "AI agents", service: "ai-content-agents" },
  { label: "AI images + video", service: "ai-content-agents" },
  { label: "Scraper blocking + security", service: "security" },
  { label: "Analytics dashboards", service: "launch-support" },
  { label: "Responsive design", service: "web-design" },
  { label: "Accessibility", service: "web-design" },
  { label: "Netlify + Railway deployment", service: "launch-support" },
];
