# Generated by Django 5.2.6 on 2026-10-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_confirmation_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='acquisition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
